# Generated by Django 6.0.3 on 2026-04-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='total_price',
            field=models.FloatField(verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='outcoming',
            name='total_price',
            field=models.FloatField(verbose_name='Общая цена'),
        ),
    ]
